/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogRouteImport } from './routes/_catalog'
import { Route as CatalogIndexRouteImport } from './routes/_catalog.index'
import { Route as PreviewNamePatternRouteImport } from './routes/preview.$name.$pattern'
import { Route as CatalogRulesTypographyRouteImport } from './routes/_catalog.rules.typography'
import { Route as CatalogRulesSpacingRouteImport } from './routes/_catalog.rules.spacing'
import { Route as CatalogRulesShapeRouteImport } from './routes/_catalog.rules.shape'
import { Route as CatalogRulesExperienceRouteImport } from './routes/_catalog.rules.experience'
import { Route as CatalogRulesColorRouteImport } from './routes/_catalog.rules.color'
import { Route as CatalogRulesBasicsRouteImport } from './routes/_catalog.rules.basics'
import { Route as CatalogComponentsNameRouteImport } from './routes/_catalog.components.$name'

const CatalogRoute = CatalogRouteImport.update({
  id: '/_catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const PreviewNamePatternRoute = PreviewNamePatternRouteImport.update({
  id: '/preview/$name/$pattern',
  path: '/preview/$name/$pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRulesTypographyRoute = CatalogRulesTypographyRouteImport.update({
  id: '/rules/typography',
  path: '/rules/typography',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogRulesSpacingRoute = CatalogRulesSpacingRouteImport.update({
  id: '/rules/spacing',
  path: '/rules/spacing',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogRulesShapeRoute = CatalogRulesShapeRouteImport.update({
  id: '/rules/shape',
  path: '/rules/shape',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogRulesExperienceRoute = CatalogRulesExperienceRouteImport.update({
  id: '/rules/experience',
  path: '/rules/experience',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogRulesColorRoute = CatalogRulesColorRouteImport.update({
  id: '/rules/color',
  path: '/rules/color',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogRulesBasicsRoute = CatalogRulesBasicsRouteImport.update({
  id: '/rules/basics',
  path: '/rules/basics',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogComponentsNameRoute = CatalogComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => CatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CatalogIndexRoute
  '/components/$name': typeof CatalogComponentsNameRoute
  '/rules/basics': typeof CatalogRulesBasicsRoute
  '/rules/color': typeof CatalogRulesColorRoute
  '/rules/experience': typeof CatalogRulesExperienceRoute
  '/rules/shape': typeof CatalogRulesShapeRoute
  '/rules/spacing': typeof CatalogRulesSpacingRoute
  '/rules/typography': typeof CatalogRulesTypographyRoute
  '/preview/$name/$pattern': typeof PreviewNamePatternRoute
}
export interface FileRoutesByTo {
  '/': typeof CatalogIndexRoute
  '/components/$name': typeof CatalogComponentsNameRoute
  '/rules/basics': typeof CatalogRulesBasicsRoute
  '/rules/color': typeof CatalogRulesColorRoute
  '/rules/experience': typeof CatalogRulesExperienceRoute
  '/rules/shape': typeof CatalogRulesShapeRoute
  '/rules/spacing': typeof CatalogRulesSpacingRoute
  '/rules/typography': typeof CatalogRulesTypographyRoute
  '/preview/$name/$pattern': typeof PreviewNamePatternRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_catalog': typeof CatalogRouteWithChildren
  '/_catalog/': typeof CatalogIndexRoute
  '/_catalog/components/$name': typeof CatalogComponentsNameRoute
  '/_catalog/rules/basics': typeof CatalogRulesBasicsRoute
  '/_catalog/rules/color': typeof CatalogRulesColorRoute
  '/_catalog/rules/experience': typeof CatalogRulesExperienceRoute
  '/_catalog/rules/shape': typeof CatalogRulesShapeRoute
  '/_catalog/rules/spacing': typeof CatalogRulesSpacingRoute
  '/_catalog/rules/typography': typeof CatalogRulesTypographyRoute
  '/preview/$name/$pattern': typeof PreviewNamePatternRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/$name'
    | '/rules/basics'
    | '/rules/color'
    | '/rules/experience'
    | '/rules/shape'
    | '/rules/spacing'
    | '/rules/typography'
    | '/preview/$name/$pattern'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/$name'
    | '/rules/basics'
    | '/rules/color'
    | '/rules/experience'
    | '/rules/shape'
    | '/rules/spacing'
    | '/rules/typography'
    | '/preview/$name/$pattern'
  id:
    | '__root__'
    | '/_catalog'
    | '/_catalog/'
    | '/_catalog/components/$name'
    | '/_catalog/rules/basics'
    | '/_catalog/rules/color'
    | '/_catalog/rules/experience'
    | '/_catalog/rules/shape'
    | '/_catalog/rules/spacing'
    | '/_catalog/rules/typography'
    | '/preview/$name/$pattern'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CatalogRoute: typeof CatalogRouteWithChildren
  PreviewNamePatternRoute: typeof PreviewNamePatternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_catalog': {
      id: '/_catalog'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_catalog/': {
      id: '/_catalog/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/preview/$name/$pattern': {
      id: '/preview/$name/$pattern'
      path: '/preview/$name/$pattern'
      fullPath: '/preview/$name/$pattern'
      preLoaderRoute: typeof PreviewNamePatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_catalog/rules/typography': {
      id: '/_catalog/rules/typography'
      path: '/rules/typography'
      fullPath: '/rules/typography'
      preLoaderRoute: typeof CatalogRulesTypographyRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/rules/spacing': {
      id: '/_catalog/rules/spacing'
      path: '/rules/spacing'
      fullPath: '/rules/spacing'
      preLoaderRoute: typeof CatalogRulesSpacingRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/rules/shape': {
      id: '/_catalog/rules/shape'
      path: '/rules/shape'
      fullPath: '/rules/shape'
      preLoaderRoute: typeof CatalogRulesShapeRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/rules/experience': {
      id: '/_catalog/rules/experience'
      path: '/rules/experience'
      fullPath: '/rules/experience'
      preLoaderRoute: typeof CatalogRulesExperienceRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/rules/color': {
      id: '/_catalog/rules/color'
      path: '/rules/color'
      fullPath: '/rules/color'
      preLoaderRoute: typeof CatalogRulesColorRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/rules/basics': {
      id: '/_catalog/rules/basics'
      path: '/rules/basics'
      fullPath: '/rules/basics'
      preLoaderRoute: typeof CatalogRulesBasicsRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/components/$name': {
      id: '/_catalog/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof CatalogComponentsNameRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogComponentsNameRoute: typeof CatalogComponentsNameRoute
  CatalogRulesBasicsRoute: typeof CatalogRulesBasicsRoute
  CatalogRulesColorRoute: typeof CatalogRulesColorRoute
  CatalogRulesExperienceRoute: typeof CatalogRulesExperienceRoute
  CatalogRulesShapeRoute: typeof CatalogRulesShapeRoute
  CatalogRulesSpacingRoute: typeof CatalogRulesSpacingRoute
  CatalogRulesTypographyRoute: typeof CatalogRulesTypographyRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogComponentsNameRoute: CatalogComponentsNameRoute,
  CatalogRulesBasicsRoute: CatalogRulesBasicsRoute,
  CatalogRulesColorRoute: CatalogRulesColorRoute,
  CatalogRulesExperienceRoute: CatalogRulesExperienceRoute,
  CatalogRulesShapeRoute: CatalogRulesShapeRoute,
  CatalogRulesSpacingRoute: CatalogRulesSpacingRoute,
  CatalogRulesTypographyRoute: CatalogRulesTypographyRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CatalogRoute: CatalogRouteWithChildren,
  PreviewNamePatternRoute: PreviewNamePatternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
